const bootstrap = () => import('./bootstrap');
const jquery = () => import('jquery');
const jszip = () => import('jszip');
const pdfmake = () => import('pdfmake');
const dataTable = () => import('datatables.net-bs5');
const buttonsBS5 = () => import('datatables.net-buttons-bs5');
const buttonsColVis = () => import('datatables.net-buttons/js/buttons.colVis.mjs');
const buttonsHtml5 = () => import('datatables.net-buttons/js/buttons.html5.mjs');
const buttonsPrint = () => import('datatables.net-buttons/js/buttons.print.mjs');
const keyTableBS5 = () => import('datatables.net-keytable-bs5');
const responsiveBS5 = () => import('datatables.net-responsive-bs5');
const scrollerBS5 = () => import('datatables.net-scroller-bs5');
const searchBuilderBS5 = () => import('datatables.net-searchbuilder-bs5');
const searchPanesBS5 = () => import('datatables.net-searchpanes-bs5');
const modelViewer = () => import('@google/model-viewer');
const chartJS = () => import('chart.js');
window.jQuery = $;
window.$ = $;